/**
 * 
 */
package com.googlecode.flickr2twitter.services.rest;

import java.io.File;

import org.restlet.Application;
import org.restlet.Context;
import org.restlet.Restlet;
import org.restlet.data.LocalReference;
import org.restlet.data.Protocol;
import org.restlet.resource.Directory;
import org.restlet.routing.Router;


/**
 * @author yayu
 *
 */
public class SocialHubRestletApplication extends Application {

	/**
	 * 
	 */
	public SocialHubRestletApplication() {
		super();
	}

	/**
	 * @param context
	 */
	public SocialHubRestletApplication(Context context) {
		super(context);
	}
	
	 /**
	 * Creates a root Restlet that will receive all incoming calls.
	 */
	@Override
	public synchronized Restlet createRoot() {
	    // Create a router Restlet that routes each call to a
	    // new Resource
	    Router router = new Router(getContext());

	    router.attachDefault(UserServerResource.class);
	    
	    
	    /*getConnectorService().getClientProtocols().add(Protocol.FILE);

        // Serve the files generated by the GWT compilation step.
        Directory dir = new Directory(getContext(), LocalReference.createFileReference(new File("/war")));
        router.attachDefault(dir);
        router.attach("/rest/user", UserServerResource.class);*/


	    return router;
	}

}
